apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-db
  template:
    metadata:
      labels:
        app: myapp-db
    spec:
      containers:
      - name: mariadb
        image: jponce508/myapp-db:v2
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-db
spec:
  ports:
    - port: 3306
  selector:
    app: myapp-db