apiVersion: apps/v1
kind: Deployment
metadata:
  name: myappweb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: mi-contenedor
        image: jponce508/tfg:v1
        ports:
        - containerPort: 80
